services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: weatherornot
      POSTGRES_USER: weatherornot
      POSTGRES_PASSWORD: weatherornot
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
