@quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:weatherornot}
quarkus.datasource.password=${DB_PASSWORD:weatherornot}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/weatherornot}
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=false
quarkus.jackson.write-dates-as-timestamps=false

